const express = require("express")
const router = express.Router()
const userController = require("../controller/userController")
const GroceryCntrller = require("../controller/groceriesController")
const CartCntrller = require("../controller/CartController")
const OrderCntrl = require("../controller/OrderCntrl")
const MailServicesCntrl = require("../controller/MailservicesCntrl")

router.post("/signup",userController.createUser)
router.post("/signIn",userController.loginUser)
router.post("/addItems",GroceryCntrller.AddItems)
router.get("/items",GroceryCntrller.getItems)
router.post("/addTocart",CartCntrller.AddTocart)
router.post("/remove",CartCntrller.RemoveFromCart)
router.post('/cart',CartCntrller.getcartItems)
router.post("/length",CartCntrller.getCartLength)
router.delete("/removefromcart",CartCntrller.deleteCart)
router.post("/forgot-password",userController.updatePassword)
router.post("/AddOrders",OrderCntrl.AddOrders)
router.post("/orders",OrderCntrl.getOrders)
router.post("/contact",MailServicesCntrl.MailSend)
module.exports = router